export enum TypeTaskEnum {
  WAITING = 'WAITING',
  DOING = 'DOING',
  REL = 'REL',
  PENDING = 'PENDING',
  DOING_PARALLER = 'DOING_PARALLER',
  DONE = 'DONE',
  CANCELE = 'CANCELE',
  PUBLISH = 'PUBLISH',
  QC_FAILED = 'QC_FAILED',
  CUSTOMER_FAILED = 'CUSTOMER_FAILED',
  CUSTOMER_UPDATE = 'CUSTOMER_UPDATE',
}
